bside-4team/4team-client

src/app/page.tsx
src/styles/theme.ts

color 세팅하기
resolve #KB-49
- `theme.ts`에 color 세팅하기
- 보시기에 사용하기 불편할 것 같으면 말씀 주세요.
1h

Feature/kb 49: color 세팅하기

---

public/image/Button/Main_Button_default.svg
public/image/Button/Main_Button_disabled.svg
public/image/Button/Main_Button_pressed.svg
src/app/example-input/page.tsx
src/components/Button/MainButton/index.tsx
src/components/Button/MainButton/page.styled.ts
src/components/Input/TextInput/index.tsx

Main Button 컴포넌트 추가
resolve #KB-57
- Main Button 컴포넌트 추가: disabled, default, default 상태 별 스타일 지정, 커스텀 가능하도록 작업
- /example-input 에서 동작 예시 확인 가능합니다.
1h

[KB-57] feat: Main Button 컴포넌트 추가

---

src/app/layout.tsx
src/app/page.tsx

[KB-79] fix: GridLayout 전체 적용
resolve #KB-79
- children을 GridLayout 으로 감싸는 작업을 했습니다.
- `<MobileLayout>
<GridLayout>{children}</GridLayout>
</MobileLayout>`
- 바로 merge 해도 될 거 같습니다
1h
[KB-79]: https://taste-dictionary.atlassian.net/browse/KB-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KB-79] fix: GridLayout 전체 적용

---

src/app/example/funnel/components/test1/index.tsx
src/app/example/funnel/components/test2/index.tsx
src/app/example/funnel/page.tsx
src/app/sign-in/components/sign-in-component/index.tsx
src/app/sign-in/components/sign-up-component/index.tsx
src/app/sign-in/page.tsx
src/hooks/useFunnel.tsx

funnel이라는 커스텀 훅 작업을 진행했습니다. 
resolve #KB-91
- Funnel 커스텀 훅 작업
- example 예시 코드 작업
사용 방법은 간단하게 Wiki에 적어뒀습니다. 
[funnel example](https://github.com/bside-4team/4team-client/wiki/example-%E2%80%90-funnel)
funnel 이라는 패턴을 적용하기 위해 필요한 코드 작업을 진행했습니다. 
funnel에 대한 자세한 사항은 toss youtube를 통해서 확인할 수 있고 참고 코드 또한 toss 오픈 소스에 작성되어있습니다! 너무나도 좋은 내용이라서 두번보고 세번보고 네번봐보세요!!!
[toss slash](https://www.youtube.com/watch?v=NwLWX2RNVcw)
[toss github useFunnel](https://github.com/toss/slash/blob/main/packages/react/use-funnel/src/useFunnel.tsx)
[toss slash](https://slash.page/ko/libraries/react/use-funnel/readme.i18n/#usefunnelstepsteps-options)
3h

[KB-91] feat : funnel 작업

---

src/app/sign-up/components/complete/index.tsx
src/app/sign-up/components/complete/page.styled.ts
src/app/sign-up/components/sign-up-component/index.tsx

회원가입 완료 UI 작업
resolve #KB-90
- 회원가입이 완료 되었습니다 ~ 위의 네모에는 아마 이미지가 들어가는 것 같은데, 들어가는 이미지 정해지면 수정하겠습니다. 
- 1h

[KB-90] feature: 회원가입 완료 UI 작업

---

src/app/sign-up/components/sign-up-component/index.tsx
src/app/sign-up/components/verify-company/index.tsx
src/app/sign-up/components/verify-company/page.styled.ts
src/app/sign-up/components/verify-number/index.tsx
src/app/sign-up/components/verify-number/page.styled.ts

회사 인증 UI 작업
resolve #KB-89
- UI 작업만 진행했습니다.
1h

[KB-89] feat: 회사 인증 UI 작업

---

src/app/sign-up/components/sign-up-component/index.tsx
src/app/sign-up/components/user-info-form/index.tsx
src/app/sign-up/components/user-info-form/page.styled.ts

- funnel 연결 
- UI 작업
피그마에 나와 있는 "인증 메일을 받지 못하셨나요?"가 잘못나온거라고 생각되서 안만들었는데 만약 추가되야한다고 하면 바로 추가하겠습니다.
1.5H

[KB-87] feat : 회원 정보 입력 UI 완료

---

.gitignore
global.d.ts
package.json
src/app/sign-up/components/region-setting/index.tsx
src/app/sign-up/components/region-setting/page.styled.ts
src/app/sign-up/components/sign-up-component/index.tsx
tsconfig.json
yarn.lock

식사 지역 설정 UI 작업
resolve #KB-88
- 우편 번호 검색: [react-daum-postcode](https://www.npmjs.com/package/react-daum-postcode) library 사용
- 우편 번호 검색 결과로 얻은 주소를 이용해 [kakao geocode](https://apis.map.kakao.com/web/sample/addr2coord/) 를 이용하여 지도에 표시
- kakao map 지도 그리기 참고: https://velog.io/@a_in/Kakao-Map-migration-part.2-get-particular-coordinate-and-address
- .env 파일을 올릴 수 없어서 카카오맵 javascript key 부분은 따로 전달 드려야 할 거 같습니다.
- 주소 검색 시 위에 모달을 띄우듯이 구현을 해서 첨부한 이미지 중 왼쪽에서 2번째 단계에서 1번째 단계로 이동을 할 때는 어떻게 가야 하는지 디자인 파트에 물어봐야 할 거 같습니다..!
3h

[KB-88] feat: 식사 지역 설정 UI 작업

---

public/image/Button/Main_Button_default.svg
public/image/Button/Main_Button_disabled.svg
public/image/Button/Main_Button_pressed.svg
src/components/c-header/index.tsx
src/components/c-header/page.styled.ts
src/components/c-nav-button/index.tsx
src/components/c-nav-button/page.styled.ts
src/components/c-pickerButton/index.tsx
src/components/c-pickerButton/page.styled.ts
src/components/layout/grid-layout/index.tsx
src/components/layout/grid-layout/page.styled.ts
src/components/layout/horizontal-layout/index.tsx
src/components/layout/horizontal-layout/page.styled.ts
src/components/layout/mobile-layout/index.tsx
src/components/layout/mobile-layout/page.styled.ts

button 이미지 변경
- button 이미지 변경
- 앞에 99번 PR 변경사항과 겹쳐있어서 보기 불편하실 것 같은데 main button 이미지만 변경하였습니다!
0.2h

[KB-100] feat: main button 이미지 변경

---

src/app/page.styled.ts
src/components/layout/mobile-layout/page.styled.ts

- GNB 하단 고정 작업 진행 ( Layout , NavContainer CSS 스타일링 수정 )
없습니다.
0.5h

[KB-101] feat : gnb 하단 고정

---

src/app/find-password/components/find-password-component/index.tsx
src/app/find-password/components/password-complete/index.tsx
src/app/find-password/components/verify-email/index.tsx
src/app/find-password/components/verify-email/page.styled.ts
src/app/find-password/page.tsx
src/app/login/page.tsx

- 비밀번호 찾기 > 이메일 인증 UI 작업
- 없습니다.
1h

[KB-109] feat : 비밀번호 찾기 > 이메일 인증 UI 작업

---

src/app/page.tsx
src/components/c-nav-button/index.tsx

GNB 리뷰 클릭 시 모달 추가
resolve #KB-127
- GNB가 app/page.tsx 안에 있는데, 아예 컴포넌트로 빼고 이 컴포넌트 안에서 클릭 시 분기를 타는 거 어떤가요??
(시간)

[KB-127] feat: GNB 리뷰 클릭 시 모달 추가

---

src/app/find-password/components/find-password-component/index.tsx
src/app/find-password/components/password-complete/index.tsx
src/app/find-password/components/verify-auth-number/index.tsx
src/app/find-password/components/verify-auth-number/page.styled.ts
src/app/find-password/components/verify-email/index.tsx
src/app/find-password/components/verify-email/page.styled.ts
src/app/find-password/page.tsx
src/app/login/page.tsx

- 인증 코드 UI 
- 인증 모달 완성
- 비밀번호 찾기에서 만든 인증코드 UI를 피그마 회원가입4에서 재사용하면 될 것 같습니다.
- 109번 PR 머지 후 머지를 진행하겠습니다!
1h

[KB-110] feat : 인증코드 UI + 인증 모달 완성

---

src/app/register-review/caution/page.styled.ts
src/app/register-review/caution/page.tsx
src/app/register-review/page.styled.ts
src/app/register-review/page.tsx
src/components/Input/TextArea/index.tsx
src/components/Input/TextArea/page.styled.ts
src/components/c-select-keyword/index.tsx
src/components/c-select-section/index.tsx
src/components/c-select-section/page.styled.ts
src/utils/index.ts

식당 리뷰 작성 페이지 UI 작업
resolve #KB-129
2.5h

[KB-129] 식당 리뷰 작성 페이지 UI 작업

---

.github/workflows/build_and_push.yml

- [kb-132] ci test-commit
- [kb-132]
- setup ci pipeline
N/A
N/A

[kb-132] ci test-commit

---

src/apis/restaurant/review.ts
src/app/page.tsx
src/app/register-review/page.tsx
src/app/register-review/restaurant/search/page.styled.ts
src/app/register-review/restaurant/search/page.tsx
src/components/c-select-category/index.tsx

식당 리뷰 등록 기능 추가
resolve #KB-158
- 식당 리뷰 등록 기능 추가
- 식당 리뷰 작성 페이지에서 식담 검색 결과가 없을 경우 모달 추가
- 없습니다
1h

[KB-158] 식당 리뷰 등록 기능 추가

---

public/image/Food/food_108.svg
public/image/Food/food_95.svg
src/app/not-found.tsx
src/app/ready/page.tsx
src/assets/common/img_error.svg
src/assets/common/img_ready.svg
src/components/c-error/index.tsx
src/components/c-error/page.styled.ts

서비스 준비 중 페이지 추가
resolve #KB-161
- 404 페이지와 서비스 준비 중 페이지가 유사해서 CError 컴포넌트로 묶어서 작업을 했습니다. (404 페이지도 수정 완료)
- KB-160 에서 파생된 브랜치 입니다.
0.2h

[KB-161] 서비스 준비 중 페이지 추가

---

src/apis/auth/index.ts
src/app/login/hooks/useLoginMutate.tsx
src/app/login/page.tsx

로그인 API 연동 작업 
- 로그인 서버 API 연결
- 작업을 진행하면서 로그인 유지할때 어떤 방식으로 유지하면 좋을지와 토큰 관리는 어떻게 하면 좋을지 고민해보면 좋을 것 같아요
- 현재 로그인 실패했을 경우 어떤 메시지도 없는 상황이라 추가적으로 정의되면 이슈 만들고 다시 올리겠습니다.
2h

[KB-154] feat : 로그인 API 연동 작업

---

src/app/sign-up/components/verify-company/index.tsx
src/components/Input/TextInput/index.tsx
src/components/Input/TextInput/page.styled.ts

(작업 내역 한줄로 요약 , 사진 대체 가능)
(작업 내역 1)  
(작업 내역 2)  
(작업 내역 3)
(특이 사항 1)  
(특이 사항 2)  
(특이 사항 3)  
(시간)

[KB-153] feat : input disabled 상태 추가

---

src/apis/http.ts
src/app/login/hooks/useLoginMutate.tsx

(작업 내역 한줄로 요약 , 사진 대체 가능)
(작업 내역 1)  
(작업 내역 2)  
(작업 내역 3)
(특이 사항 1)  
(특이 사항 2)  
(특이 사항 3)  
(시간)

save login token

---

src/app/select-menu/page.tsx
src/app/select-restaurant/page.tsx
src/components/c-select-category/index.tsx
src/components/c-select-keyword/index.tsx

선택 초기화 버튼 활성화 에러
resolve #KB-168
- 선택 초기화 버튼 활성화 에러 수정
- 선택 초기화 버튼 기능 에러 수
- 없습니다
0.1h

[KB-168] 선택 초기화 버튼 활성화 에러

---

src/app/sign-up/components/opt-in-marketing/index.tsx
src/app/sign-up/components/opt-in-marketing/page.styled.ts
src/app/sign-up/components/sign-up-component/index.tsx

(작업 내역 한줄로 요약 , 사진 대체 가능)
(작업 내역 1)  
(작업 내역 2)  
(작업 내역 3)
(특이 사항 1)  
(특이 사항 2)  
(특이 사항 3)  
(시간)

[KB-169] feat : 개인정보처리방침 마무리

---

src/app/sign-up/hooks/query/useAccountAuthCodeMutate.ts

(작업 내역 한줄로 요약 , 사진 대체 가능)
(작업 내역 1)  
(작업 내역 2)  
(작업 내역 3)
(특이 사항 1)  
(특이 사항 2)  
(특이 사항 3)  
(시간)

[KB-171] fix : 이메일 전송 인증 텍스트 수정

---

package.json
src/app/layout.tsx
src/components/Toast/index.tsx
src/components/Toast/page.styled.ts
yarn.lock

Toast 컴포넌트 추가
resolve #KB-184
- [react-toastify](https://www.npmjs.com/package/react-toastify)를 사용하여 토스트 컴포넌트 구현
- 토스트 사용 방법
```
import { toast } from "react-toastify";
onClick={() => toast("토스트 메세지")}
```
0.5h

[KB-184] feat: Toast 컴포넌트 추가

---

src/apis/example/nestia.ts

nestia 적용하기
resolve #KB-156
- src/apis/example/nestia.ts 확인하시면 됩니다.
- KB-151 브랜치에서 생성하였습니다. 
- 자꾸 CORS 에러가 나오는데, 저희가 더 처리해야 되는 게 있을까요??
0.5h

[KB-156] nestia 적용하기
